using Moq;
using project.Models;

public class F05_EnrollmentCourseService_Tests
{
    private readonly Mock<IEnrollmentCourseRepository> _enrollmentRepo = new();
    private readonly Mock<ICourseRepository> _courseRepo = new();
    private readonly Mock<IStudentRepository> _studentRepo = new();
    private readonly Mock<ICourseContentRepository> _courseContentRepo = new();
    private readonly Mock<ILessonRepository> _lessonRepo = new();
    private readonly Mock<ILessonProgressRepository> _lessonProgressRepo = new();
    private readonly Mock<IExamRepository> _examRepo = new();
    private readonly Mock<ISubmissionExamRepository> _submissionExamRepo = new();
    private readonly Mock<IRequestRefundCourseRepository> _refundRepo = new();
    private readonly Mock<IAdminRepository> _adminRepo = new();
    private readonly Mock<IUserRepository> _userRepo = new();

    private EnrollmentCourseService BuildService() => new(
        _enrollmentRepo.Object, _courseRepo.Object, _studentRepo.Object,
        _courseContentRepo.Object, _lessonRepo.Object, _examRepo.Object,
        _lessonProgressRepo.Object, _submissionExamRepo.Object, _refundRepo.Object,
        _adminRepo.Object, _userRepo.Object);

    private static string G() => Guid.NewGuid().ToString();

    // Test Case ID: UT_F05_01
    [Fact] public async Task TC01_CreateEnrollment_FreeCourse_Success(){var c=G();var s=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_studentRepo.Setup(x=>x.IsStudentExistAsync(s)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(false);var sut=BuildService();await sut.CreateEnrollmentAsync(c,s);_enrollmentRepo.Verify(x=>x.CreateEnrollmentAsync(It.IsAny<Enrollment_course>()),Times.Once);}    
    // Test Case ID: UT_F05_02
    [Fact] public async Task TC02_CreateEnrollment_PaidCourse_Success(){var c=G();var s=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_studentRepo.Setup(x=>x.IsStudentExistAsync(s)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(false);var sut=BuildService();await sut.CreateEnrollmentAsync(c,s);_enrollmentRepo.Verify(x=>x.CreateEnrollmentAsync(It.Is<Enrollment_course>(e=>e.Status=="active")),Times.Once);}    
    // Test Case ID: UT_F05_03
    [Fact] public async Task TC03_CreateEnrollment_CourseNotFound(){var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.CreateEnrollmentAsync(G(),G()));}
    // Test Case ID: UT_F05_04
    [Fact] public async Task TC04_CreateEnrollment_StudentNotFound(){var c=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_studentRepo.Setup(x=>x.IsStudentExistAsync(It.IsAny<string>())).ReturnsAsync(false);var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.CreateEnrollmentAsync(c,G()));}
    // Test Case ID: UT_F05_05
    [Fact] public async Task TC05_CreateEnrollment_DuplicateBlocked(){var c=G();var s=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_studentRepo.Setup(x=>x.IsStudentExistAsync(s)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(true);var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.CreateEnrollmentAsync(c,s));}
    // Test Case ID: UT_F05_06
    [Fact] public async Task TC06_CreateEnrollment_InvalidCourseGuid(){var sut=BuildService();await Assert.ThrowsAsync<ArgumentException>(()=>sut.CreateEnrollmentAsync("bad-guid",G()));}
    // Test Case ID: UT_F05_07
    [Fact] public async Task TC07_CreateEnrollment_StudentNotFound_WithAnotherInputSet(){var c=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_studentRepo.Setup(x=>x.IsStudentExistAsync(It.IsAny<string>())).ReturnsAsync(false);var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.CreateEnrollmentAsync(c,G()));}
    // Test Case ID: UT_F05_08
    [Fact] public async Task TC08_CreateEnrollment_SetEnrolledAt(){var c=G();var s=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_studentRepo.Setup(x=>x.IsStudentExistAsync(s)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(false);Enrollment_course? cap=null;_enrollmentRepo.Setup(x=>x.CreateEnrollmentAsync(It.IsAny<Enrollment_course>())).Callback<Enrollment_course>(e=>cap=e).Returns(Task.CompletedTask);var sut=BuildService();await sut.CreateEnrollmentAsync(c,s);Assert.NotNull(cap);Assert.True(cap!.EnrolledAt<=DateTime.UtcNow);}    
    // Test Case ID: UT_F05_09
    [Fact] public async Task TC09_CreateEnrollment_DefaultCertificate(){var c=G();var s=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_studentRepo.Setup(x=>x.IsStudentExistAsync(s)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(false);Enrollment_course? cap=null;_enrollmentRepo.Setup(x=>x.CreateEnrollmentAsync(It.IsAny<Enrollment_course>())).Callback<Enrollment_course>(e=>cap=e).Returns(Task.CompletedTask);var sut=BuildService();await sut.CreateEnrollmentAsync(c,s);Assert.Equal("No Certificate",cap!.CertificateUrl);}    
    // Test Case ID: UT_F05_10
    [Fact] public async Task TC10_CreateEnrollment_RepoCallOnce(){var c=G();var s=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_studentRepo.Setup(x=>x.IsStudentExistAsync(s)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(false);var sut=BuildService();await sut.CreateEnrollmentAsync(c,s);_enrollmentRepo.Verify(x=>x.CreateEnrollmentAsync(It.IsAny<Enrollment_course>()),Times.Once);}    

    // Test Case ID: UT_F05_11
    [Fact] public async Task TC11_IsEnrolled_ReturnTrue(){var c=G();var s=G();_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(true);var sut=BuildService();Assert.True(await sut.IsEnrolledInCourseAsync(s,c));}
    // Test Case ID: UT_F05_12
    [Fact] public async Task TC12_IsEnrolled_ReturnFalse(){var c=G();var s=G();_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(false);var sut=BuildService();Assert.False(await sut.IsEnrolledInCourseAsync(s,c));}
    // Test Case ID: UT_F05_13
    [Fact] public async Task TC13_GetDetail_Success(){var c=G();var e=G();var u=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Student=new Student{User=new User{Id=u,FullName="A"}},Course=new Course{Title="C",Status="published",Teacher=new Teacher{User=new User{Id=G()}},Category=new Category()}});var sut=BuildService();var dto=await sut.GetEnrollmentByIdAsync(u,c,e);Assert.Equal("A",dto.StudentName);}    
    // Test Case ID: UT_F05_14
    [Fact] public async Task TC14_GetDetail_UserNotFound(){var c=G();var e=G();var u=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(false);var sut=BuildService();await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>sut.GetEnrollmentByIdAsync(u,c,e));}
    // Test Case ID: UT_F05_15
    [Fact] public async Task TC15_GetDetail_OwnerMismatch(){var c=G();var e=G();var u=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Student=new Student{User=new User{Id=G()}}});var sut=BuildService();await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>sut.GetEnrollmentByIdAsync(u,c,e));}
    // Test Case ID: UT_F05_16
    [Fact] public async Task TC16_GetDetail_EnrollmentCourseMismatch(){var c=G();var e=G();var u=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=G(),Student=new Student{User=new User{Id=u}}});var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.GetEnrollmentByIdAsync(u,c,e));}
    // Test Case ID: UT_F05_17
    [Fact] public async Task TC17_GetDetail_EnrollmentNotFound(){var c=G();var e=G();var u=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync((Enrollment_course?)null);var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.GetEnrollmentByIdAsync(u,c,e));}
    // Test Case ID: UT_F05_18
    [Fact] public async Task TC18_GetDetail_FallbackStudentName(){var c=G();var e=G();var u=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Student=new Student{User=new User{Id=u,FullName=null!}},Course=new Course{Title="C",Status="published",Teacher=new Teacher{User=new User{Id=G()}},Category=new Category()}});var sut=BuildService();var dto=await sut.GetEnrollmentByIdAsync(u,c,e);Assert.Equal("Unknown",dto.StudentName);}    
    // Test Case ID: UT_F05_19
    [Fact] public async Task TC19_GetDetail_FallbackCourseTitle(){var c=G();var e=G();var u=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Student=new Student{User=new User{Id=u,FullName="A"}},Course=new Course{Title=null!,Status="published",Teacher=new Teacher{User=new User{Id=G()}},Category=new Category()}});var sut=BuildService();var dto=await sut.GetEnrollmentByIdAsync(u,c,e);Assert.Equal("Unknown Title",dto.CourseName);}    
    // Test Case ID: UT_F05_20
    [Fact] public async Task TC20_GetDetail_FallbackStatus(){var c=G();var e=G();var u=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Student=new Student{User=new User{Id=u,FullName="A"}},Course=new Course{Title="C",Status="published",Teacher=new Teacher{User=new User{Id=G()}},Category=new Category()},Status=null!});var sut=BuildService();var dto=await sut.GetEnrollmentByIdAsync(u,c,e);Assert.Equal("Unknown",dto.Status);}    

    // Test Case ID: UT_F05_21
    [Fact] public async Task TC21_UpdateProgress_ByLesson_Success(){var c=G();var s=G();var l=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrollmentByStudentAndCourseIdAsync(s,c)).ReturnsAsync(new Enrollment_course{CourseId=c,StudentId=s,Status="active"});_lessonRepo.Setup(x=>x.LessonExistsAsync(l)).ReturnsAsync(true);_lessonProgressRepo.Setup(x=>x.ExistsAsync(l,s)).ReturnsAsync(false);_courseContentRepo.Setup(x=>x.TotalLessons(c)).ReturnsAsync(10);_lessonProgressRepo.Setup(x=>x.CountCompletedLessonsAsync(c,s)).ReturnsAsync(2);_examRepo.Setup(x=>x.TotalExamsInCourseAsync(c)).ReturnsAsync(2);_submissionExamRepo.Setup(x=>x.CountPassExamsAsync(c,s,It.IsAny<double>())).ReturnsAsync(1);var sut=BuildService();await sut.UpdateProgressEnrollmentAsync(s,c,new EnrollmentProgressUpdateDTO{LessonId=l});_enrollmentRepo.Verify(x=>x.UpdateProgressEnrollmentAsync(It.IsAny<Enrollment_course>()),Times.Once);}    
    // Test Case ID: UT_F05_22
    [Fact] public async Task TC22_UpdateProgress_ByExam_Success(){var c=G();var s=G();var ex=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrollmentByStudentAndCourseIdAsync(s,c)).ReturnsAsync(new Enrollment_course{CourseId=c,StudentId=s,Status="active"});_examRepo.Setup(x=>x.GetExamStatusAsync(ex)).ReturnsAsync((true,true));_courseContentRepo.Setup(x=>x.TotalLessons(c)).ReturnsAsync(0);_lessonProgressRepo.Setup(x=>x.CountCompletedLessonsAsync(c,s)).ReturnsAsync(0);_examRepo.Setup(x=>x.TotalExamsInCourseAsync(c)).ReturnsAsync(1);_submissionExamRepo.Setup(x=>x.CountPassExamsAsync(c,s,It.IsAny<double>())).ReturnsAsync(1);var sut=BuildService();await sut.UpdateProgressEnrollmentAsync(s,c,new EnrollmentProgressUpdateDTO{ExamId=ex});_enrollmentRepo.Verify(x=>x.UpdateProgressEnrollmentAsync(It.IsAny<Enrollment_course>()),Times.Once);}    
    // Test Case ID: UT_F05_23
    [Fact] public async Task TC23_UpdateProgress_BothLessonAndExam(){var sut=BuildService();await Assert.ThrowsAsync<ArgumentException>(()=>sut.UpdateProgressEnrollmentAsync(G(),G(),new EnrollmentProgressUpdateDTO{LessonId=G(),ExamId=G()}));}
    // Test Case ID: UT_F05_24
    [Fact] public async Task TC24_UpdateProgress_BothNull(){var sut=BuildService();await Assert.ThrowsAsync<ArgumentException>(()=>sut.UpdateProgressEnrollmentAsync(G(),G(),new EnrollmentProgressUpdateDTO()));}
    // Test Case ID: UT_F05_25
    [Fact] public async Task TC25_UpdateProgress_CourseNotFound(){var s=G();var c=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(false);var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.UpdateProgressEnrollmentAsync(s,c,new EnrollmentProgressUpdateDTO{LessonId=G()}));}
    // Test Case ID: UT_F05_26
    [Fact] public async Task TC26_UpdateProgress_EnrollmentNotFound(){var s=G();var c=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrollmentByStudentAndCourseIdAsync(s,c)).ReturnsAsync((Enrollment_course?)null);var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.UpdateProgressEnrollmentAsync(s,c,new EnrollmentProgressUpdateDTO{LessonId=G()}));}
    // Test Case ID: UT_F05_27
    [Fact] public async Task TC27_UpdateProgress_NotActive(){var s=G();var c=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrollmentByStudentAndCourseIdAsync(s,c)).ReturnsAsync(new Enrollment_course{CourseId=c,StudentId=s,Status="cancelled"});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.UpdateProgressEnrollmentAsync(s,c,new EnrollmentProgressUpdateDTO{LessonId=G()}));}
    // Test Case ID: UT_F05_28
    [Fact] public async Task TC28_UpdateProgress_LessonNotFound(){var s=G();var c=G();var l=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrollmentByStudentAndCourseIdAsync(s,c)).ReturnsAsync(new Enrollment_course{CourseId=c,StudentId=s,Status="active"});_lessonRepo.Setup(x=>x.LessonExistsAsync(l)).ReturnsAsync(false);var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.UpdateProgressEnrollmentAsync(s,c,new EnrollmentProgressUpdateDTO{LessonId=l}));}
    // Test Case ID: UT_F05_29
    [Fact] public async Task TC29_UpdateProgress_AlreadyCompleted_NoDoubleCount(){var s=G();var c=G();var l=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrollmentByStudentAndCourseIdAsync(s,c)).ReturnsAsync(new Enrollment_course{CourseId=c,StudentId=s,Status="active"});_lessonRepo.Setup(x=>x.LessonExistsAsync(l)).ReturnsAsync(true);_lessonProgressRepo.Setup(x=>x.ExistsAsync(l,s)).ReturnsAsync(true);var sut=BuildService();await sut.UpdateProgressEnrollmentAsync(s,c,new EnrollmentProgressUpdateDTO{LessonId=l});_enrollmentRepo.Verify(x=>x.UpdateProgressEnrollmentAsync(It.IsAny<Enrollment_course>()),Times.Never);}    
    // Test Case ID: UT_F05_30
    [Fact] public async Task TC30_UpdateProgress_ReachCompletedThreshold(){var s=G();var c=G();var l=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrollmentByStudentAndCourseIdAsync(s,c)).ReturnsAsync(new Enrollment_course{CourseId=c,StudentId=s,Status="active"});_lessonRepo.Setup(x=>x.LessonExistsAsync(l)).ReturnsAsync(true);_lessonProgressRepo.Setup(x=>x.ExistsAsync(l,s)).ReturnsAsync(false);_courseContentRepo.Setup(x=>x.TotalLessons(c)).ReturnsAsync(1);_lessonProgressRepo.Setup(x=>x.CountCompletedLessonsAsync(c,s)).ReturnsAsync(1);_examRepo.Setup(x=>x.TotalExamsInCourseAsync(c)).ReturnsAsync(1);_submissionExamRepo.Setup(x=>x.CountPassExamsAsync(c,s,It.IsAny<double>())).ReturnsAsync(1);var sut=BuildService();await sut.UpdateProgressEnrollmentAsync(s,c,new EnrollmentProgressUpdateDTO{LessonId=l});_enrollmentRepo.Verify(x=>x.UpdateProgressEnrollmentAsync(It.Is<Enrollment_course>(e=>e.Status=="Completed")),Times.Once);}    

    // Test Case ID: UT_F05_31
    [Fact] public async Task TC31_RequestCancel_Eligible_Success(){var u=G();var c=G();var e=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Status="active",EnrolledAt=DateTime.UtcNow,Progress=10m,StudentId=G(),Student=new Student{User=new User{Id=u}}});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c)).ReturnsAsync(new Course{Id=c,Price=100m,Status="published",Teacher=new Teacher{User=new User{Id=G()}},Category=new Category(),Title="paid"});var sut=BuildService();await sut.RequestCancelEnrollmentAsync(u,c,e,new RequestCancelEnrollmentDTO{ReasonRequest="r"});_refundRepo.Verify(x=>x.CreateRequestRefundCourseAsync(It.IsAny<RefundRequestCourse>()),Times.Once);}    
    // Test Case ID: UT_F05_32
    [Fact] public async Task TC32_RequestCancel_CourseNotFound(){_courseRepo.Setup(x=>x.CourseExistsAsync(It.IsAny<string>())).ReturnsAsync(false);var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.RequestCancelEnrollmentAsync(G(),G(),G(),new RequestCancelEnrollmentDTO{ReasonRequest="r"}));}
    // Test Case ID: UT_F05_33
    [Fact] public async Task TC33_RequestCancel_EnrollmentNotFound(){var u=G();var c=G();var e=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync((Enrollment_course?)null);var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.RequestCancelEnrollmentAsync(u,c,e,new RequestCancelEnrollmentDTO{ReasonRequest="r"}));}
    // Test Case ID: UT_F05_34
    [Fact] public async Task TC34_RequestCancel_UserNotFound(){var u=G();var c=G();var e=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Student=new Student{User=new User{Id=u}}});_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(false);var sut=BuildService();await Assert.ThrowsAsync<KeyNotFoundException>(()=>sut.RequestCancelEnrollmentAsync(u,c,e,new RequestCancelEnrollmentDTO{ReasonRequest="r"}));}
    // Test Case ID: UT_F05_35
    [Fact] public async Task TC35_RequestCancel_NotOwner(){var u=G();var c=G();var e=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Student=new Student{User=new User{Id=G()}}});_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);var sut=BuildService();await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>sut.RequestCancelEnrollmentAsync(u,c,e,new RequestCancelEnrollmentDTO{ReasonRequest="r"}));}
    // Test Case ID: UT_F05_36
    [Fact] public async Task TC36_RequestCancel_NotActive(){var u=G();var c=G();var e=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Status="Completed",Student=new Student{User=new User{Id=u}}});_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.RequestCancelEnrollmentAsync(u,c,e,new RequestCancelEnrollmentDTO{ReasonRequest="r"}));}
    // Test Case ID: UT_F05_37
    [Fact] public async Task TC37_RequestCancel_FreeCourseBlocked(){var u=G();var c=G();var e=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Status="active",EnrolledAt=DateTime.UtcNow,Progress=0m,Student=new Student{User=new User{Id=u}}});_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_courseRepo.Setup(x=>x.GetCourseByIdAsync(c)).ReturnsAsync(new Course{Id=c,Price=0m,Status="published",Teacher=new Teacher{User=new User{Id=G()}},Category=new Category(),Title="free"});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.RequestCancelEnrollmentAsync(u,c,e,new RequestCancelEnrollmentDTO{ReasonRequest="r"}));}
    // Test Case ID: UT_F05_38
    [Fact] public async Task TC38_RequestCancel_AfterTwoDaysBlocked(){var u=G();var c=G();var e=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Status="active",EnrolledAt=DateTime.UtcNow.AddDays(-3),Progress=0m,Student=new Student{User=new User{Id=u}}});_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_courseRepo.Setup(x=>x.GetCourseByIdAsync(c)).ReturnsAsync(new Course{Id=c,Price=100m,Status="published",Teacher=new Teacher{User=new User{Id=G()}},Category=new Category(),Title="paid"});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.RequestCancelEnrollmentAsync(u,c,e,new RequestCancelEnrollmentDTO{ReasonRequest="r"}));}
    // Test Case ID: UT_F05_39
    [Fact] public async Task TC39_RequestCancel_Progress50Blocked(){var u=G();var c=G();var e=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.GetEnrrollmentByIdAsync(e)).ReturnsAsync(new Enrollment_course{Id=e,CourseId=c,Status="active",EnrolledAt=DateTime.UtcNow,Progress=50m,Student=new Student{User=new User{Id=u}}});_userRepo.Setup(x=>x.IsUserExistAsync(u)).ReturnsAsync(true);_courseRepo.Setup(x=>x.GetCourseByIdAsync(c)).ReturnsAsync(new Course{Id=c,Price=100m,Status="published",Teacher=new Teacher{User=new User{Id=G()}},Category=new Category(),Title="paid"});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.RequestCancelEnrollmentAsync(u,c,e,new RequestCancelEnrollmentDTO{ReasonRequest="r"}));}
    // Test Case ID: UT_F05_40
    [Fact] public async Task TC40_CreateEnrollment_DefaultsExact(){var c=G();var s=G();_courseRepo.Setup(x=>x.CourseExistsAsync(c)).ReturnsAsync(true);_studentRepo.Setup(x=>x.IsStudentExistAsync(s)).ReturnsAsync(true);_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(false);Enrollment_course? cap=null;_enrollmentRepo.Setup(x=>x.CreateEnrollmentAsync(It.IsAny<Enrollment_course>())).Callback<Enrollment_course>(e=>cap=e).Returns(Task.CompletedTask);var sut=BuildService();await sut.CreateEnrollmentAsync(c,s);Assert.Equal("active",cap!.Status);Assert.Equal(0m,cap.Progress);Assert.Equal("No Certificate",cap.CertificateUrl);}    
}
