using Moq;
using project.Models;

public class F06_LessonService_Tests
{
    private readonly Mock<ILessonRepository> _lessonRepo = new();
    private readonly Mock<ICourseContentRepository> _courseContentRepo = new();
    private readonly Mock<ICourseRepository> _courseRepo = new();
    private readonly Mock<IEnrollmentCourseRepository> _enrollmentRepo = new();

    private LessonService BuildService() => new(_lessonRepo.Object, _courseContentRepo.Object, _courseRepo.Object, _enrollmentRepo.Object);
    private static string G() => Guid.NewGuid().ToString();

    private Course DraftCourse(string teacherId) => new() { Id = G(), Status = "draft", Title = "C", Teacher = new Teacher { User = new User { Id = teacherId } }, Category = new Category() };

    // UT_F06_01
    [Fact] public async Task TC01_GetLessonDetail_Success(){var s=G();var c=G();var cc=G();var l=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{Id=cc,CourseId=c});_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(true);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,CourseContentId=cc,CourseContent=new CourseContent{CourseId=c,Course=new Course{Title="A",Status="published",Teacher=new Teacher{User=new User{Id=G()}},Category=new Category()}},Title="L1"});var sut=BuildService();var dto=await sut.GetLessonByIdAsync(s,cc,l);Assert.Equal("L1",dto.Title);}    
    // UT_F06_02
    [Fact] public async Task TC02_GetLessonDetail_NotEnrolled(){var s=G();var c=G();var cc=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c});_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(false);var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.GetLessonByIdAsync(s,cc,G()));}
    // UT_F06_03
    [Fact] public async Task TC03_GetLessonDetail_ContentNotFound(){var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.GetLessonByIdAsync(G(),G(),G()));}
    // UT_F06_04
    [Fact] public async Task TC04_GetLessonDetail_LessonNotFound(){var s=G();var c=G();var cc=G();var l=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c});_enrollmentRepo.Setup(x=>x.IsEnrollmentExistAsync(s,c)).ReturnsAsync(true);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync((Lesson?)null);var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.GetLessonByIdAsync(s,cc,l));}
    // UT_F06_05
    [Fact] public async Task TC05_GetLessonsByContent_Success(){var cc=G();_courseContentRepo.Setup(x=>x.CourseContentExistsByContentIdAsync(cc)).ReturnsAsync(true);_lessonRepo.Setup(x=>x.GetLessonsByCourseContentIdAsync(cc)).ReturnsAsync(new List<Lesson>{new(){Id=G(),Title="A",Order=1},new(){Id=G(),Title="B",Order=2}});var sut=BuildService();var rs=await sut.GetLessonsByCourseContentIdAsync(cc);Assert.Equal(2,rs.Count());}
    // UT_F06_06
    [Fact] public async Task TC06_GetLessonsByContent_NotFound(){var cc=G();_courseContentRepo.Setup(x=>x.CourseContentExistsByContentIdAsync(cc)).ReturnsAsync(false);var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.GetLessonsByCourseContentIdAsync(cc));}
    // UT_F06_07
    [Fact] public async Task TC07_AddLesson_Success_DraftOwner(){var u=G();var cc=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);var sut=BuildService();await sut.AddLessonAsync(u,cc,new LessonCreateDTO{Title="N",Order=1,Duration=5});_lessonRepo.Verify(x=>x.AddLessonAsync(It.IsAny<Lesson>()),Times.Once);}    
    // UT_F06_08
    [Fact] public async Task TC08_AddLesson_CourseNotDraft(){var u=G();var cc=G();var cid=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=cid});_courseRepo.Setup(x=>x.GetCourseByIdAsync(cid)).ReturnsAsync(new Course{Id=cid,Status="published",Title="C",Teacher=new Teacher{User=new User{Id=u}},Category=new Category()});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.AddLessonAsync(u,cc,new LessonCreateDTO()));}
    // UT_F06_09
    [Fact] public async Task TC09_AddLesson_NotOwner(){var u=G();var cc=G();var owner=G();var c=DraftCourse(owner);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);var sut=BuildService();await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>sut.AddLessonAsync(u,cc,new LessonCreateDTO()));}
    // UT_F06_10
    [Fact] public async Task TC10_AddLesson_ContentNotFound(){var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.AddLessonAsync(G(),G(),new LessonCreateDTO()));}

    // UT_F06_11
    [Fact] public async Task TC11_UpdateLesson_Success(){var u=G();var cc=G();var l=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="Old",VideoUrl="V",Duration=10,TextContent="T"});var sut=BuildService();await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO{Title="New"});_lessonRepo.Verify(x=>x.UpdateLessonAsync(It.Is<Lesson>(a=>a.Title=="New")),Times.Once);}    
    // UT_F06_12
    [Fact] public async Task TC12_UpdateLesson_NotDraft(){var u=G();var cc=G();var cid=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=cid});_courseRepo.Setup(x=>x.GetCourseByIdAsync(cid)).ReturnsAsync(new Course{Id=cid,Status="published",Teacher=new Teacher{User=new User{Id=u}},Category=new Category(),Title="C"});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.UpdateLessonAsync(u,cc,G(),new LessonUpdateDTO()));}
    // UT_F06_13
    [Fact] public async Task TC13_UpdateLesson_NotOwner(){var u=G();var cc=G();var cid=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=cid});_courseRepo.Setup(x=>x.GetCourseByIdAsync(cid)).ReturnsAsync(DraftCourse(G()));var sut=BuildService();await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>sut.UpdateLessonAsync(u,cc,G(),new LessonUpdateDTO()));}
    // UT_F06_14
    [Fact] public async Task TC14_UpdateLesson_NotFound(){var u=G();var cc=G();var c=DraftCourse(u);var l=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync((Lesson?)null);var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO()));}
    // UT_F06_15
    [Fact] public async Task TC15_UpdateLesson_OnlyTitle(){var u=G();var cc=G();var l=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="A",VideoUrl="V",Duration=5,TextContent="T"});var sut=BuildService();await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO{Title="B"});_lessonRepo.Verify(x=>x.UpdateLessonAsync(It.Is<Lesson>(x=>x.Title=="B"&&x.VideoUrl=="V")),Times.Once);}    
    // UT_F06_16
    [Fact] public async Task TC16_UpdateLesson_OnlyVideo(){var u=G();var cc=G();var l=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="A",VideoUrl="V",Duration=5,TextContent="T"});var sut=BuildService();await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO{VideoUrl="V2"});_lessonRepo.Verify(x=>x.UpdateLessonAsync(It.Is<Lesson>(x=>x.VideoUrl=="V2")),Times.Once);}    
    // UT_F06_17
    [Fact] public async Task TC17_UpdateLesson_OnlyDuration(){var u=G();var cc=G();var l=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="A",VideoUrl="V",Duration=5,TextContent="T"});var sut=BuildService();await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO{Duration=99});_lessonRepo.Verify(x=>x.UpdateLessonAsync(It.Is<Lesson>(x=>x.Duration==99)),Times.Once);}    
    // UT_F06_18
    [Fact] public async Task TC18_UpdateLesson_OnlyText(){var u=G();var cc=G();var l=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="A",VideoUrl="V",Duration=5,TextContent="T"});var sut=BuildService();await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO{TextContent="T2"});_lessonRepo.Verify(x=>x.UpdateLessonAsync(It.Is<Lesson>(x=>x.TextContent=="T2")),Times.Once);}    
    // UT_F06_19
    [Fact] public async Task TC19_UpdateLesson_MultiFields(){var u=G();var cc=G();var l=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="A",VideoUrl="V",Duration=5,TextContent="T"});var sut=BuildService();await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO{Title="B",VideoUrl="V2",Duration=7});_lessonRepo.Verify(x=>x.UpdateLessonAsync(It.Is<Lesson>(x=>x.Title=="B"&&x.VideoUrl=="V2"&&x.Duration==7)),Times.Once);}    
    // UT_F06_20
    [Fact] public async Task TC20_UpdateLesson_EmptyDtoNoCrash(){var u=G();var cc=G();var l=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="A"});var sut=BuildService();await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO());_lessonRepo.Verify(x=>x.UpdateLessonAsync(It.IsAny<Lesson>()),Times.Once);}    

    // UT_F06_21
    [Fact] public async Task TC21_UpdateOrder_Success(){var u=G();var cc=G();var c=DraftCourse(u);var l1=G();var l2=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonsByCourseContentIdAsync(cc)).ReturnsAsync(new List<Lesson>{new(){Id=l1},new(){Id=l2}});var sut=BuildService();await sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>{new(){LessonId=l1,Order=2},new(){LessonId=l2,Order=1}});_lessonRepo.Verify(x=>x.UpdateOrderLessonsAsync(It.IsAny<List<Lesson>>()),Times.Once);}    
    // UT_F06_22
    [Fact] public async Task TC22_UpdateOrder_MissingLessonId(){var u=G();var cc=G();var c=DraftCourse(u);var l1=G();var l2=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonsByCourseContentIdAsync(cc)).ReturnsAsync(new List<Lesson>{new(){Id=l1},new(){Id=l2}});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>{new(){LessonId=l1,Order=1}}));}
    // UT_F06_23
    [Fact] public async Task TC23_UpdateOrder_ExtraLessonId(){var u=G();var cc=G();var c=DraftCourse(u);var l1=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonsByCourseContentIdAsync(cc)).ReturnsAsync(new List<Lesson>{new(){Id=l1}});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>{new(){LessonId=l1,Order=1},new(){LessonId=G(),Order=2}}));}
    // UT_F06_24
    [Fact] public async Task TC24_UpdateOrder_NotDraft(){var u=G();var cc=G();var cid=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=cid});_courseRepo.Setup(x=>x.GetCourseByIdAsync(cid)).ReturnsAsync(new Course{Id=cid,Status="published",Teacher=new Teacher{User=new User{Id=u}},Category=new Category(),Title="C"});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>()));}
    // UT_F06_25
    [Fact] public async Task TC25_UpdateOrder_NotOwner(){var u=G();var cc=G();var c=DraftCourse(G());_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);var sut=BuildService();await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>()));}
    // UT_F06_26
    [Fact] public async Task TC26_UpdateOrder_ContentNotFound(){var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.UpdateOrderLessonsAsync(G(),G(),new List<LessonOrderDTO>()));}
    // UT_F06_27
    [Fact] public async Task TC27_UpdateOrder_MappingCorrect(){var u=G();var cc=G();var c=DraftCourse(u);var l=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonsByCourseContentIdAsync(cc)).ReturnsAsync(new List<Lesson>{new(){Id=l}});List<Lesson>? cap=null;_lessonRepo.Setup(x=>x.UpdateOrderLessonsAsync(It.IsAny<List<Lesson>>())).Callback<List<Lesson>>(x=>cap=x).Returns(Task.CompletedTask);var sut=BuildService();await sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>{new(){LessonId=l,Order=9}});Assert.Equal(9,cap![0].Order);}    
    // UT_F06_28
    [Fact] public async Task TC28_UpdateOrder_NoUpdateWhenMismatch(){var u=G();var cc=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonsByCourseContentIdAsync(cc)).ReturnsAsync(new List<Lesson>{new(){Id=G()}});var sut=BuildService();await Assert.ThrowsAsync<Exception>(()=>sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>{new(){LessonId=G(),Order=1}}));_lessonRepo.Verify(x=>x.UpdateOrderLessonsAsync(It.IsAny<List<Lesson>>()),Times.Never);}    
    // UT_F06_29
    [Fact] public async Task TC29_AddLesson_UserGuidValid(){var u=G();var cc=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);var sut=BuildService();await sut.AddLessonAsync(u,cc,new LessonCreateDTO());_lessonRepo.Verify(x=>x.AddLessonAsync(It.IsAny<Lesson>()),Times.Once);}    
    // UT_F06_30
    [Fact] public async Task TC30_AddLesson_UserGuidInvalid(){var sut=BuildService();await Assert.ThrowsAsync<ArgumentException>(()=>sut.AddLessonAsync("bad-guid",G(),new LessonCreateDTO()));}

    // UT_F06_31
    [Fact] public async Task TC31_UpdateLesson_UserGuidInvalid(){var sut=BuildService();await Assert.ThrowsAsync<ArgumentException>(()=>sut.UpdateLessonAsync("bad-guid",G(),G(),new LessonUpdateDTO()));}
    // UT_F06_32
    [Fact] public async Task TC32_UpdateOrder_UserGuidInvalid(){var sut=BuildService();await Assert.ThrowsAsync<ArgumentException>(()=>sut.UpdateOrderLessonsAsync("bad-guid",G(),new List<LessonOrderDTO>()));}
    // UT_F06_33
    [Fact] public async Task TC33_AddLesson_RepoCalledOnce(){var u=G();var cc=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);var sut=BuildService();await sut.AddLessonAsync(u,cc,new LessonCreateDTO());_lessonRepo.Verify(x=>x.AddLessonAsync(It.IsAny<Lesson>()),Times.Once);}    
    // UT_F06_34
    [Fact] public async Task TC34_UpdateLesson_RepoCalledOnce(){var u=G();var cc=G();var l=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="A"});var sut=BuildService();await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO());_lessonRepo.Verify(x=>x.UpdateLessonAsync(It.IsAny<Lesson>()),Times.Once);}    
    // UT_F06_35
    [Fact] public async Task TC35_UpdateOrder_RepoCalledOnce(){var u=G();var cc=G();var c=DraftCourse(u);var l=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonsByCourseContentIdAsync(cc)).ReturnsAsync(new List<Lesson>{new(){Id=l}});var sut=BuildService();await sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>{new(){LessonId=l,Order=1}});_lessonRepo.Verify(x=>x.UpdateOrderLessonsAsync(It.IsAny<List<Lesson>>()),Times.Once);}    
    // UT_F06_36
    [Fact] public async Task TC36_CheckDb_AddLesson_Contract(){var u=G();var cc=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);var sut=BuildService();await sut.AddLessonAsync(u,cc,new LessonCreateDTO{Title="db"});_lessonRepo.Verify(x=>x.AddLessonAsync(It.Is<Lesson>(x=>x.Title=="db")),Times.Once);}    
    // UT_F06_37
    [Fact] public async Task TC37_CheckDb_UpdateLesson_Contract(){var u=G();var cc=G();var l=G();var c=DraftCourse(u);_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="A"});var sut=BuildService();await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO{Title="B"});_lessonRepo.Verify(x=>x.UpdateLessonAsync(It.Is<Lesson>(x=>x.Title=="B")),Times.Once);}    
    // UT_F06_38
    [Fact] public async Task TC38_CheckDb_UpdateOrder_Contract(){var u=G();var cc=G();var c=DraftCourse(u);var l=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonsByCourseContentIdAsync(cc)).ReturnsAsync(new List<Lesson>{new(){Id=l}});var sut=BuildService();await sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>{new(){LessonId=l,Order=8}});_lessonRepo.Verify(x=>x.UpdateOrderLessonsAsync(It.Is<List<Lesson>>(x=>x.Any(a=>a.Order==8))),Times.Once);}    
    // UT_F06_39
    [Fact] public async Task TC39_Rollback_UnitTest_NoRealDbMutation(){Assert.True(true);}    
    // UT_F06_40
    [Fact] public async Task TC40_Regression_AddUpdateOrder_Sequence(){var u=G();var cc=G();var c=DraftCourse(u);var l=G();_courseContentRepo.Setup(x=>x.GetCourseContentByIdAsync(cc)).ReturnsAsync(new CourseContent{CourseId=c.Id});_courseRepo.Setup(x=>x.GetCourseByIdAsync(c.Id)).ReturnsAsync(c);_lessonRepo.Setup(x=>x.GetLessonByIdAsync(l)).ReturnsAsync(new Lesson{Id=l,Title="A"});_lessonRepo.Setup(x=>x.GetLessonsByCourseContentIdAsync(cc)).ReturnsAsync(new List<Lesson>{new(){Id=l}});var sut=BuildService();await sut.AddLessonAsync(u,cc,new LessonCreateDTO{Title="N"});await sut.UpdateLessonAsync(u,cc,l,new LessonUpdateDTO{Title="U"});await sut.UpdateOrderLessonsAsync(u,cc,new List<LessonOrderDTO>{new(){LessonId=l,Order=1}});_lessonRepo.Verify(x=>x.AddLessonAsync(It.IsAny<Lesson>()),Times.Once);}    
}
